modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/SleepyTrousers/EnderCore/issues" #optional
license="CC0"

[[mods]] #mandatory
modId="endercore" #mandatory
version="${file.jarVersion}" #mandatory
displayName="EnderCore" #mandatory
updateJSONURL="http://ci.tterrag.com/job/EnderCore" #optional
displayURL="http://enderio.com" #optional
logoFile="examplemod.png" #optional
credits="" #optional
authors="tterrag, CrazyPants, HenryLoenwind, Rover656, HypherionSA, agnor99" #optional
description="Library mod used by EnderIO, EnderZoo, and others"

[[dependencies.endercore]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.endercore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
